name: Update Version

on:
  push:
    branches:
      - main


jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v4.0.0
      with:
        preset: angular

    - name: Bump Version
      run: npm version --no-git-tag-version ${{ steps.generate-changelog.outputs.version }}

    - name: Commit and push changes
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"
        git add package.json
        git commit -m "Bump version to ${{ steps.generate-changelog.outputs.version }}"
        git remote add origin-second https://${{ secrets.TOKEN_ACTION }}@github.com/$GITHUB_REPOSITORY
        git push origin-second
