name: Update Version

on:
  push:
    branches:
      - main


jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Use the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        preset: angular
