name: Update Version

on:
  push:
    branches:
      - main


jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # Use the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        preset: angular

    - name: Bump Version
      id: bump-version
      run: |
        # Generate a new version
        echo "name=version" >> "$(jq -r '.version' package.json)"
        
    - name: Commit and push changes
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"
        git add package.json
        git commit -m "Bump version to ${{ steps.bump-version.outputs.version }}"
        git tag -a v${{ steps.bump-version.outputs.version }} -m "Version ${{ steps.bump-version.outputs.version }}"
        git remote add origin-second https://${{ secrets.TOKEN_ACTION }}@github.com/$GITHUB_REPOSITORY
        git push origin-second v${{ steps.bump-version.outputs.version }}
        git push origin-second
        
    - name: Get the last tag
      id: last_tag
      run: |
        git fetch --tags
        last_tag=$(git describe --tags --abbrev=0)
        echo "name=tag" >> "$last_tag"
          
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.last_tag.outputs.tag }}
        tag_name: ${{ steps.last_tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_ACTION }}
