name: Bump version
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ACTION }}
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v4.0.0
      with:
        github-token: ${{ secrets.TOKEN_ACTION }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: ''
        output-file: 'CHANGELOG.md'
